name = "podcast-feed"
compatibility_date = "2023-01-01"

[define]
"import.meta.vitest" = "undefined"

[[r2_buckets]]
binding = "PRIVATE_PODCAST"
bucket_name = "private-podcast"

[[d1_databases]]
binding = "DB"
database_name = "podcast-db"
database_id = "1a0e1abe-7cce-4112-9b9a-9b41813e034a"
