name = "podcast-feed"
compatibility_date = "2023-01-01"
keep_vars = true

[vars]
HOST = ""
USERNAME = ""
PASSWORD = ""

[define]
"import.meta.vitest" = "undefined"

[[r2_buckets]]
binding = "PRIVATE_PODCAST"
bucket_name = "private-podcast"

